### ISSUE TITLE
About methods on stronger baseline models

### ISSUE THREAD

**Issue by lxtGH** [wanglixilinx/DSRL#1]
Hi! Recently I read your CVPR paper, it is very interesting idea. But I have a confusing part is that on the baseline.  Why the baseline are so low ? How about the results on Stronger Baseline.

**Comment by wanglixilinx** [comment]
@lxtGH  thanks very much for your attention.  We reproduce the baseline for ESPentv2 with 256x512 w/o considering the class-weight.  so the mIoU is nearly -2%  compared with the ESPnetv2 paper.

**Comment by lxtGH** [comment]
I mean the stronger baselines are above 78+ mIoU on Cityscapes.

**Comment by zhiwenfan** [comment]
Similar question, wish you can answer about it, Thanks!

**Comment by wanglixilinx** [comment]
Hi, we implement our experiments with a low-resolution input (512x512).
