### ISSUE TITLE
When the code can be released?Thanks. 

### ISSUE THREAD

**Issue by gnsci** [wanglixilinx/DSRL#18]
When the code can be released?Thanks.

**Comment by Dootmaan** [comment]
hi there i've made my own implementation and hope that can help. checkout https://github.com/Dootmaan/DSRL

**Comment by Dootmaan** [comment]
> When the code can be released?Thanks.

hi there i've made my own implementation and maybe u would like to checkout https://github.com/Dootmaan/DSRL

**Comment by wanglixilinx** [comment]
Hi,  Sam,
  Thanks very much for your attention and your implementation work.  Sorry for the long time for source code release caused of the legal scan stuck, Later I will check your repo and give you a feedback as soon as possible. Thanks again.

Best,
From Li

**Comment by wanglixilinx** [comment]
We release our code in: https://github.com/Xilinx/DSRL
