### ISSUE TITLE
求解SSIR中的Decoder

### ISSUE THREAD

**Issue by AMzhanghan** [wanglixilinx/DSRL#4]
最近在研究你们的paper，很棒的idea！ 请问下SSIR中的Decoder是怎么实现的？ 是简单的双线性上采样还是用什么方法实现的？

**Comment by wanglixilinx** [comment]
Hi @AMzhanghan ， thanks for your attention. For the SISR deocder, you can refer  the design of  SOTA methods for image super-resolution task.  And  in our paper, we follow the Post-upsampling Super-resolution method  (such as "Real-time single image and video super-resolution using an efficient sub-pixel convolutional neural network" and so on) to design the SISR branch.
