### ISSUE TITLE
关于FA的输入问题

### ISSUE THREAD

**Issue by Dootmaan** [wanglixilinx/DSRL#5]
您好，拜读了文章，有一个问题还不敢确定。请问一下FA的两个输入是只有Segmentation分支和SR分支的瓶颈层特征是吗？

**Comment by wanglixilinx** [comment]
Hi, @Dootmaan,  we use the last feature maps before the prediction layer both from SSSR and SISR branches to compute the similarity matrixes, respectively,  then these two similarity matrixes are the inputs of FA module to compute the FA loss.
