### ISSUE TITLE
similarity matrix

### ISSUE THREAD

**Issue by Bubble-bubble77** [wanglixilinx/DSRL#6]
I recently read your paperand I have a question that  how is “ semantic segmentation similarity matrix or SISR similarity matrix” in FA part realized?  Looking forward to your reply as soon as possible

**Comment by wanglixilinx** [comment]
Hi, @bubblehhhahaha ,
 the similarity matrix S= torch.bmm(F.transpose, F),  Here the shape for F is W' H' x C', the shape for F.transpose is 
C' x W'H', so the shape of similarity matrix S  is W'H' x W'H'.  And we also do normalization to the feature F (set p=2 in Equation (2)) for stability.

**Comment by Bubble-bubble77** [comment]
Thank you very much!!
